<?php
namespace App\Transformers\Transaksi;

use App\Transformers\Transformer;

class AssetTransformer extends Transformer
{
    protected $list = [
        "norec" => "noRec",
        "kdprofile" => "kdProfile",
        "statusenabled" => "statusEnabled",
        "objectasalprodukfk" => "asalProdukFk",
        "asal_produk.asalproduk" => "asalProduk",
        "objectbahanprodukfk" => "bahanProdukFk",
        "bahan_produk.namabahanproduk" => "namaBahanProduk",
        "bpkbatasnama" => "bpkbBatasNama",
        "dayalistrik" => "dayaListrik",
        "fungsikegunaan" => "fungsiKegunaan",
        "harga" => "harga",
        "harganetto" => "hargaNetto",
        "hargapenyusutan" => "hargaPenyusutan",
        "hargapertambahan" => "hargaPertambahan",
        "hargasatuanrevaluasi" => "hargaSatuanRevaluasi",
        "objectjeniskontruksifk" => "jenisKontruksiFk",
        "jenis_kontruksi.jeniskontruksi" => "jenisKontruksi",
        "objectjenissetifikatfk" => "jenisSetifikatFk",
        "jenis_setifikat.jenissetifikat" => "jenisSetifikat",
        "kapasitasmesin" => "kapasitasMesin",
        "kdaspac" => "kdAspac",
        "kdbmn" => "kdBmn",
        "kdrsabhk" => "kdRsabhk",
        "objectkelompokasetfk" => "kelompokAsetFk",
        "kelompokaset.kelompokaset" => "kelompokAset",
        "keteranganlainya" => "keteranganLainnya",
        "objectklasifikasiteknologifk" => "klasifikasiTeknologiFk",
        "klasifikasitek_no_logi.klasifikasiteknologi" => "klasifikasiTeknologi",
        "objectkondisiprodukawalfk" => "kondisiProdukAwalFk",
        "kondisi_produk_awal.kondisiprodukawal" => "kondisiProdukAwal",
        "objectkondisiprodukcurrentfk" => "kondisiProdukCurrentFk",
        "kondisi_produk_current.kondisiprodukcurrent" => "kondisiProdukCurrent",
        "lblebar" => "lbLebar",
        "lbpanjang" => "lbaPanjang",
        "lbtinggi" => "lbTinggi",
        "objectlokasifk" => "lokasiFk",
        "lokasi.namalokasi" => "namaLokasi",
        "ltlebar" => "ltLebar",
        "ltpanjang" => "ltPanjang",
        "masaberlakusertifikat" => "masaBerlakuSertifikat",
        "objectmerkprodukfk" => "merkProdukFk",
        "merk_produk.merkproduk" => "merkProduk",
        "namamodel" => "namaModel",
        "namapengguna" => "namaPengguna",
        "namaruasjalan" => "namaRuasjalan",
        "nobpkb" => "noBpkb",
        "nomesin" => "noMesin",
        "nomodel" => "noModel",
        "nopolisi" => "noPolisi",
        "norangka" => "noRanGka",
        "noregisteraset" => "noRegisterAset",
        "noregisteraset_int" => "noRegisterAsetInt",
        "noseri" => "noSeri",
        "noserial" => "noSerial",
        "nosertifikat" => "noSertifikat",
        "nostruktext" => "noStrukText",
        "objectpegawaipenggunafk" => "pegawaiPenggunaFk",
        "pegawai_pengguna.pegawaipengguna" => "pegawaiPengguna",
        "objectprodukfk" => "produkFk",
        "produk.namaproduk" => "namaProduk",
        "objectprodusenprodukfk" => "produsenProdukFk",
        "produsen_produk.namaprodusenproduk" => "namaProdusenProduk",
        "qtyprodukaset" => "qtyProdukAset",
        "qtylantai" => "qtyLantai",
        "objectrekananfk" => "rekananFk",
        "rek_an_an.namarekanan" => "namaRekanan",
        "objectruanganfk" => "ruanganFk",
        "ruangan.namaruangan" => "namaRuangan",
        "objectruanganposisicurrentfk" => "ruanganPosisiCurrentFk",
        "ruangan_posisicurrent.ruanganposisicurrent" => "ruanganPosisiCurrent",
        "objectsatuanasetfk" => "satuanAsetFk",
        "satuan_aset.satuanaset" => "satuanAset",
        "sertifikatatasnama" => "sertifikatAtasNama",
        "objecttahunperolehanfk" => "tahunPerolehanFk",
        "tahunperoleh_an.tahunperolehan" => "tahunPerolehan",
        "tglpenerimaanaset" => "tglPenerimaanAset",
        "tglproduksi" => "tglProduksi",
        "tglregisteraset" => "tglRegisterAset",
        "tglstrukterima" => "tglStrukTerima",
        "totalsisaumurekonomistahun" => "totalSisaUmurEkonomisTahun",
        "totalsudahbertambah" => "totalSudahBertambah",
        "totalsudahmenyusut" => "totalSudahMenyusut",
        "objecttypeprodukfk" => "typeProdukFk",
        "type_produk.typeproduk" => "typeProduk",
        "umurekonomisrevaluasitahun" => "umurekoNoMisrevaluasitahun",
        "objectusiaasetfk" => "usiaAsetFk",
        "usiaaset.usiaaset" => "usiaAset",
        "objectwarnaprodukfk" => "warnaProdukFk",
        "warna_produk.warnaproduk" => "warnaProduk",
        "noregistrasiasset" => "noRegistrasiAsset",
        "qtyaset" => "qtyAset",
        //        "objectalamatfk"     => "alamatFk",
        //        "alamat.alamat"     => "alamat",
        //        "objectkondisiasetfk"     => "kondisiAsetFk",
        //        "kondisiaset.kondisiaset"     => "kondisiAset",

    ];
}
 