<?php
namespace App\Transformers\Master;

use App\Transformers\Transformer;

class PegawaiTransformer extends Transformer
{
  protected $list = [
    "id" => "id",
    "kdprofile" => "kdProfile",
    "statusenabled" => "statusEnabled",
    "kodeexternal" => "kodeExternal",
    "namaexternal" => "namaExternal",
    "norec" => "noRec",
    "reportdisplay" => "reportDisplay",
    "nosk_hasilfk" => "noSkHasilFk",
    "nostruk_ttujuanlastfk" => "noStrukTTujuanLastFk",
    "objectagamafk" => "agamaFk",
    "agama.agama" => "agama",
    "objectdetailkategorypegawaifk" => "detailKategoryPegawaiFk",
    "detail_kategory_pegawai.detailkategorypegawai" => "detailKategoryPegawai",
    "objecteselonfk" => "eselonFk",
    "eselon.eselon" => "eselon",
    "objectgolongandarahfk" => "golonganDarahFk",
    "golongan_darah.golongandarah" => "golonganDarah",
    "objectjabatanfungsionalfk" => "jabatanFungsionalFk",
    "jabatan.namajabatan" => "namaJabatan",
    "objectjabatanlamarfk" => "jabatanLamarFk",
    "objectjabatanstrukturalfk" => "jabatanStrukturalFk",
    "objectjeniskelaminfk" => "jenisKelaminFk",
    "jenis_kelamin.jeniskelamin" => "jenisKelamin",
    "objectjenispegawaifk" => "jenisPegawaiFk",
    "jenis_pegawai.jenispegawai" => "jenisPegawai",
    "objectjenispegawailamarfk" => "jenisPegawaiLamarFk",
    "objectkualifikasijurusanfk" => "kualifikasiJurusanFk",
    "kualifikasi_jurus_an.kualifikasijurusan" => "kualifikasiJurusan",
    "objectnegarafk" => "negaraFk",
    "negara.namanegara" => "namaNegara",
    "objectpangkatfk" => "pangkatFk",
    "pangkat.namapangkat" => "namaPangkat",
    "objectpendidikanterakhirfk" => "pendidikanTerakhirFk",
    "pendidikan.pendidikan" => "pendidikan",
    "objectrangetotalnilaiscorefk" => "rangeTotalNilaiScoreFk",
    "range.namarange" => "namaRange",
    "objectruangankerjafk" => "ruanganKerjaFk",
    "ruangan.namaruangan" => "namaRuangan",
    "objectstatuspegawaifk" => "statusPegawaiFk",
    "status_pegawai.statuspegawai" => "statusPegawai",
    "objectstatusperkawinanfk" => "statusPerkawinanFk",
    "status_perkawinan.statusperkawinan" => "statusPerkawinan",
    "objectsukufk" => "sukuFk",
    "suku.suku" => "suku",
    "objecttypepegawaifk" => "typePegawaiFk",
    "type_pegawai.typepegawai" => "typePegawai",
    "bankrekeningatasnama" => "bankRekeningAtasNama",
    "bankrekeningnama" => "bankRekeningNama",
    "bankrekeningnomor" => "bankRekeningNomor",
    "fingerprintid" => "fingerPrintId",
    "namakeluarga" => "namaKeluarga",
    "namalengkap" => "namaLengkap",
    "namapanggilan" => "namaPanggilan",
    "nik_intern" => "nikIntern",
    "nip_pns" => "nippns",
    "noidentitas" => "noIdEntitas",
    "npwp" => "npwp",
    "photodiri" => "photoDiri",
    "qpegawai" => "qPegawai",
    "qtyanak" => "qtyAnak",
    "qtytanggungan" => "qtyTanggungan",
    "qtytotaljiwa" => "qtyTotalJiwa",
    "statusrhesus" => "statusRhesus",
    "tempatlahir" => "tempatLahir",
    "tgldaftarfingerprint" => "tglDaftarFingerPrint",
    "tglkeluar" => "tglKeluar",
    "tgllahir" => "tglLahir",
    "tglmasuk" => "tglMasuk",
    "totalnilaiscore" => "totalNilaiScore",
    "nikintern" => "nikIntern",
    "nippns" => "nipPns",
    //        "objectdokumensuratlamarfk"     => "dokumenSuratLamarFk",
    //        "dokumen.dokumen"     => "dokumen",
    //        "objectptkpfk"     => "ptkpFk",
    //        "penghasilan_tidak_kena_pajak.penghasilantidakkenapajak"     => "penghasilanTidakKenaPajak",
    //        "objectpegawaiatasanfk"     => "pegawaiAtasAnFk",
    //        "pegawai.pegawai"     => "pegawai",
    //        "objectpegawaifk"     => "pegawaiFk",
    //        "objectpegawaipembimbingfk"     => "pegawaiPembimbingFk",
    //        "objecttitlefk"     => "titleFk",
    //        "title_pasien.titlepasien"     => "titlePasien",

  ];
}
 